language: go
go:
  - "1.10.1"
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - make get-dev-dependencies
script:
  - make test
after_success:
  - sh $(pwd)/scripts/coverage.sh --coveralls
